/*
 * generated by Xtext 2.25.0
 */
package model.myzdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyZDslUiModule extends AbstractMyZDslUiModule {

	public MyZDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
