/*
 * generated by Xtext 2.25.0
 */
package model.myzdsl.parser.antlr;

import com.google.inject.Inject;
import model.myzdsl.parser.antlr.internal.InternalMyZDslParser;
import model.myzdsl.services.MyZDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MyZDslParser extends AbstractAntlrParser {

	@Inject
	private MyZDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMyZDslParser createParser(XtextTokenStream stream) {
		return new InternalMyZDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MyZModel";
	}

	public MyZDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyZDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
