/*
 * generated by Xtext 2.25.0
 */
package model.myzdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyZDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("model/myzdsl/parser/antlr/internal/InternalMyZDsl.tokens");
	}
}
