/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see model.myzdsl.myZDsl.MyZDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyZDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myZDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.myzdsl.model/MyZDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myZDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyZDslPackage eINSTANCE = model.myzdsl.myZDsl.impl.MyZDslPackageImpl.init();

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.MyZModelImpl <em>My ZModel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.MyZModelImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getMyZModel()
   * @generated
   */
  int MY_ZMODEL = 0;

  /**
   * The feature id for the '<em><b>Systemstatespace</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_ZMODEL__SYSTEMSTATESPACE = 0;

  /**
   * The feature id for the '<em><b>Initialstate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_ZMODEL__INITIALSTATE = 1;

  /**
   * The feature id for the '<em><b>Schemas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_ZMODEL__SCHEMAS = 2;

  /**
   * The number of structural features of the '<em>My ZModel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MY_ZMODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.SystemStateSpaceImpl <em>System State Space</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.SystemStateSpaceImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSystemStateSpace()
   * @generated
   */
  int SYSTEM_STATE_SPACE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE__PREDICATE = 2;

  /**
   * The number of structural features of the '<em>System State Space</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.SystemStateSpacePredicateImpl <em>System State Space Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.SystemStateSpacePredicateImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSystemStateSpacePredicate()
   * @generated
   */
  int SYSTEM_STATE_SPACE_PREDICATE = 2;

  /**
   * The feature id for the '<em><b>Vas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE_PREDICATE__VAS = 0;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE_PREDICATE__FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Predicate Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE_PREDICATE__PREDICATE_VAR = 2;

  /**
   * The number of structural features of the '<em>System State Space Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_STATE_SPACE_PREDICATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.InitialStateImpl <em>Initial State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.InitialStateImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getInitialState()
   * @generated
   */
  int INITIAL_STATE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__VARIABLES = 1;

  /**
   * The feature id for the '<em><b>Pred</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE__PRED = 2;

  /**
   * The number of structural features of the '<em>Initial State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_STATE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.SchemaImpl <em>Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.SchemaImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSchema()
   * @generated
   */
  int SCHEMA = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__NAME = 0;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__STATE = 1;

  /**
   * The feature id for the '<em><b>Name Schema</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__NAME_SCHEMA = 2;

  /**
   * The feature id for the '<em><b>Vars Input</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__VARS_INPUT = 3;

  /**
   * The feature id for the '<em><b>Vars Output</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__VARS_OUTPUT = 4;

  /**
   * The feature id for the '<em><b>Predicates</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA__PREDICATES = 5;

  /**
   * The number of structural features of the '<em>Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.PredicateImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 5;

  /**
   * The feature id for the '<em><b>Vas Input</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__VAS_INPUT = 0;

  /**
   * The feature id for the '<em><b>Belongs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__BELONGS = 1;

  /**
   * The feature id for the '<em><b>Belongs Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__BELONGS_VARIABLE = 2;

  /**
   * The feature id for the '<em><b>Vas Output</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__VAS_OUTPUT = 3;

  /**
   * The feature id for the '<em><b>Vas State Change</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__VAS_STATE_CHANGE = 4;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.VariablesImpl <em>Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.VariablesImpl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getVariables()
   * @generated
   */
  int VARIABLES = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES__NAME = 0;

  /**
   * The number of structural features of the '<em>Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.PredicatePostCondition1Impl <em>Predicate Post Condition1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.PredicatePostCondition1Impl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicatePostCondition1()
   * @generated
   */
  int PREDICATE_POST_CONDITION1 = 7;

  /**
   * The feature id for the '<em><b>Condition11</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION1__CONDITION11 = 0;

  /**
   * The feature id for the '<em><b>Condition12</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION1__CONDITION12 = 1;

  /**
   * The feature id for the '<em><b>Condition13</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION1__CONDITION13 = 2;

  /**
   * The number of structural features of the '<em>Predicate Post Condition1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION1_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl <em>Predicate Post Condition2</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl
   * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicatePostCondition2()
   * @generated
   */
  int PREDICATE_POST_CONDITION2 = 8;

  /**
   * The feature id for the '<em><b>Condition21</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION2__CONDITION21 = 0;

  /**
   * The feature id for the '<em><b>Condition22</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION2__CONDITION22 = 1;

  /**
   * The feature id for the '<em><b>Condition23</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION2__CONDITION23 = 2;

  /**
   * The number of structural features of the '<em>Predicate Post Condition2</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_POST_CONDITION2_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.MyZModel <em>My ZModel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>My ZModel</em>'.
   * @see model.myzdsl.myZDsl.MyZModel
   * @generated
   */
  EClass getMyZModel();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.MyZModel#getSystemstatespace <em>Systemstatespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Systemstatespace</em>'.
   * @see model.myzdsl.myZDsl.MyZModel#getSystemstatespace()
   * @see #getMyZModel()
   * @generated
   */
  EReference getMyZModel_Systemstatespace();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.MyZModel#getInitialstate <em>Initialstate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Initialstate</em>'.
   * @see model.myzdsl.myZDsl.MyZModel#getInitialstate()
   * @see #getMyZModel()
   * @generated
   */
  EReference getMyZModel_Initialstate();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.MyZModel#getSchemas <em>Schemas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schemas</em>'.
   * @see model.myzdsl.myZDsl.MyZModel#getSchemas()
   * @see #getMyZModel()
   * @generated
   */
  EReference getMyZModel_Schemas();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.SystemStateSpace <em>System State Space</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System State Space</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpace
   * @generated
   */
  EClass getSystemStateSpace();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.SystemStateSpace#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpace#getName()
   * @see #getSystemStateSpace()
   * @generated
   */
  EAttribute getSystemStateSpace_Name();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.SystemStateSpace#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpace#getVariables()
   * @see #getSystemStateSpace()
   * @generated
   */
  EReference getSystemStateSpace_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.SystemStateSpace#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predicate</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpace#getPredicate()
   * @see #getSystemStateSpace()
   * @generated
   */
  EReference getSystemStateSpace_Predicate();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate <em>System State Space Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System State Space Predicate</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpacePredicate
   * @generated
   */
  EClass getSystemStateSpacePredicate();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getVas <em>Vas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vas</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpacePredicate#getVas()
   * @see #getSystemStateSpacePredicate()
   * @generated
   */
  EReference getSystemStateSpacePredicate_Vas();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpacePredicate#getFunction()
   * @see #getSystemStateSpacePredicate()
   * @generated
   */
  EAttribute getSystemStateSpacePredicate_Function();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getPredicateVar <em>Predicate Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate Var</em>'.
   * @see model.myzdsl.myZDsl.SystemStateSpacePredicate#getPredicateVar()
   * @see #getSystemStateSpacePredicate()
   * @generated
   */
  EReference getSystemStateSpacePredicate_PredicateVar();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.InitialState <em>Initial State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial State</em>'.
   * @see model.myzdsl.myZDsl.InitialState
   * @generated
   */
  EClass getInitialState();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.InitialState#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see model.myzdsl.myZDsl.InitialState#getName()
   * @see #getInitialState()
   * @generated
   */
  EAttribute getInitialState_Name();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.InitialState#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see model.myzdsl.myZDsl.InitialState#getVariables()
   * @see #getInitialState()
   * @generated
   */
  EReference getInitialState_Variables();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.InitialState#getPred <em>Pred</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pred</em>'.
   * @see model.myzdsl.myZDsl.InitialState#getPred()
   * @see #getInitialState()
   * @generated
   */
  EReference getInitialState_Pred();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.Schema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema</em>'.
   * @see model.myzdsl.myZDsl.Schema
   * @generated
   */
  EClass getSchema();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.Schema#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see model.myzdsl.myZDsl.Schema#getName()
   * @see #getSchema()
   * @generated
   */
  EAttribute getSchema_Name();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.Schema#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see model.myzdsl.myZDsl.Schema#getState()
   * @see #getSchema()
   * @generated
   */
  EAttribute getSchema_State();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.Schema#getNameSchema <em>Name Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name Schema</em>'.
   * @see model.myzdsl.myZDsl.Schema#getNameSchema()
   * @see #getSchema()
   * @generated
   */
  EAttribute getSchema_NameSchema();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Schema#getVarsInput <em>Vars Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars Input</em>'.
   * @see model.myzdsl.myZDsl.Schema#getVarsInput()
   * @see #getSchema()
   * @generated
   */
  EReference getSchema_VarsInput();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Schema#getVarsOutput <em>Vars Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vars Output</em>'.
   * @see model.myzdsl.myZDsl.Schema#getVarsOutput()
   * @see #getSchema()
   * @generated
   */
  EReference getSchema_VarsOutput();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Schema#getPredicates <em>Predicates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predicates</em>'.
   * @see model.myzdsl.myZDsl.Schema#getPredicates()
   * @see #getSchema()
   * @generated
   */
  EReference getSchema_Predicates();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see model.myzdsl.myZDsl.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Predicate#getVasInput <em>Vas Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vas Input</em>'.
   * @see model.myzdsl.myZDsl.Predicate#getVasInput()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_VasInput();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.Predicate#getBelongs <em>Belongs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Belongs</em>'.
   * @see model.myzdsl.myZDsl.Predicate#getBelongs()
   * @see #getPredicate()
   * @generated
   */
  EAttribute getPredicate_Belongs();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.Predicate#getBelongsVariable <em>Belongs Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Belongs Variable</em>'.
   * @see model.myzdsl.myZDsl.Predicate#getBelongsVariable()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_BelongsVariable();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Predicate#getVasOutput <em>Vas Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vas Output</em>'.
   * @see model.myzdsl.myZDsl.Predicate#getVasOutput()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_VasOutput();

  /**
   * Returns the meta object for the containment reference list '{@link model.myzdsl.myZDsl.Predicate#getVasStateChange <em>Vas State Change</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Vas State Change</em>'.
   * @see model.myzdsl.myZDsl.Predicate#getVasStateChange()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_VasStateChange();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.Variables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variables</em>'.
   * @see model.myzdsl.myZDsl.Variables
   * @generated
   */
  EClass getVariables();

  /**
   * Returns the meta object for the attribute '{@link model.myzdsl.myZDsl.Variables#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see model.myzdsl.myZDsl.Variables#getName()
   * @see #getVariables()
   * @generated
   */
  EAttribute getVariables_Name();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.PredicatePostCondition1 <em>Predicate Post Condition1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Post Condition1</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition1
   * @generated
   */
  EClass getPredicatePostCondition1();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition11 <em>Condition11</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition11</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition1#getCondition11()
   * @see #getPredicatePostCondition1()
   * @generated
   */
  EReference getPredicatePostCondition1_Condition11();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition12 <em>Condition12</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition12</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition1#getCondition12()
   * @see #getPredicatePostCondition1()
   * @generated
   */
  EReference getPredicatePostCondition1_Condition12();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition13 <em>Condition13</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition13</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition1#getCondition13()
   * @see #getPredicatePostCondition1()
   * @generated
   */
  EReference getPredicatePostCondition1_Condition13();

  /**
   * Returns the meta object for class '{@link model.myzdsl.myZDsl.PredicatePostCondition2 <em>Predicate Post Condition2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Post Condition2</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition2
   * @generated
   */
  EClass getPredicatePostCondition2();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition21 <em>Condition21</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition21</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition2#getCondition21()
   * @see #getPredicatePostCondition2()
   * @generated
   */
  EReference getPredicatePostCondition2_Condition21();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition22 <em>Condition22</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition22</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition2#getCondition22()
   * @see #getPredicatePostCondition2()
   * @generated
   */
  EReference getPredicatePostCondition2_Condition22();

  /**
   * Returns the meta object for the containment reference '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition23 <em>Condition23</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition23</em>'.
   * @see model.myzdsl.myZDsl.PredicatePostCondition2#getCondition23()
   * @see #getPredicatePostCondition2()
   * @generated
   */
  EReference getPredicatePostCondition2_Condition23();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyZDslFactory getMyZDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.MyZModelImpl <em>My ZModel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.MyZModelImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getMyZModel()
     * @generated
     */
    EClass MY_ZMODEL = eINSTANCE.getMyZModel();

    /**
     * The meta object literal for the '<em><b>Systemstatespace</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_ZMODEL__SYSTEMSTATESPACE = eINSTANCE.getMyZModel_Systemstatespace();

    /**
     * The meta object literal for the '<em><b>Initialstate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_ZMODEL__INITIALSTATE = eINSTANCE.getMyZModel_Initialstate();

    /**
     * The meta object literal for the '<em><b>Schemas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MY_ZMODEL__SCHEMAS = eINSTANCE.getMyZModel_Schemas();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.SystemStateSpaceImpl <em>System State Space</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.SystemStateSpaceImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSystemStateSpace()
     * @generated
     */
    EClass SYSTEM_STATE_SPACE = eINSTANCE.getSystemStateSpace();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_STATE_SPACE__NAME = eINSTANCE.getSystemStateSpace_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_SPACE__VARIABLES = eINSTANCE.getSystemStateSpace_Variables();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_SPACE__PREDICATE = eINSTANCE.getSystemStateSpace_Predicate();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.SystemStateSpacePredicateImpl <em>System State Space Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.SystemStateSpacePredicateImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSystemStateSpacePredicate()
     * @generated
     */
    EClass SYSTEM_STATE_SPACE_PREDICATE = eINSTANCE.getSystemStateSpacePredicate();

    /**
     * The meta object literal for the '<em><b>Vas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_SPACE_PREDICATE__VAS = eINSTANCE.getSystemStateSpacePredicate_Vas();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_STATE_SPACE_PREDICATE__FUNCTION = eINSTANCE.getSystemStateSpacePredicate_Function();

    /**
     * The meta object literal for the '<em><b>Predicate Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_STATE_SPACE_PREDICATE__PREDICATE_VAR = eINSTANCE.getSystemStateSpacePredicate_PredicateVar();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.InitialStateImpl <em>Initial State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.InitialStateImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getInitialState()
     * @generated
     */
    EClass INITIAL_STATE = eINSTANCE.getInitialState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL_STATE__NAME = eINSTANCE.getInitialState_Name();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_STATE__VARIABLES = eINSTANCE.getInitialState_Variables();

    /**
     * The meta object literal for the '<em><b>Pred</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_STATE__PRED = eINSTANCE.getInitialState_Pred();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.SchemaImpl <em>Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.SchemaImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getSchema()
     * @generated
     */
    EClass SCHEMA = eINSTANCE.getSchema();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA__NAME = eINSTANCE.getSchema_Name();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA__STATE = eINSTANCE.getSchema_State();

    /**
     * The meta object literal for the '<em><b>Name Schema</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA__NAME_SCHEMA = eINSTANCE.getSchema_NameSchema();

    /**
     * The meta object literal for the '<em><b>Vars Input</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA__VARS_INPUT = eINSTANCE.getSchema_VarsInput();

    /**
     * The meta object literal for the '<em><b>Vars Output</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA__VARS_OUTPUT = eINSTANCE.getSchema_VarsOutput();

    /**
     * The meta object literal for the '<em><b>Predicates</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA__PREDICATES = eINSTANCE.getSchema_Predicates();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.PredicateImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Vas Input</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__VAS_INPUT = eINSTANCE.getPredicate_VasInput();

    /**
     * The meta object literal for the '<em><b>Belongs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICATE__BELONGS = eINSTANCE.getPredicate_Belongs();

    /**
     * The meta object literal for the '<em><b>Belongs Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__BELONGS_VARIABLE = eINSTANCE.getPredicate_BelongsVariable();

    /**
     * The meta object literal for the '<em><b>Vas Output</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__VAS_OUTPUT = eINSTANCE.getPredicate_VasOutput();

    /**
     * The meta object literal for the '<em><b>Vas State Change</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__VAS_STATE_CHANGE = eINSTANCE.getPredicate_VasStateChange();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.VariablesImpl <em>Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.VariablesImpl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getVariables()
     * @generated
     */
    EClass VARIABLES = eINSTANCE.getVariables();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLES__NAME = eINSTANCE.getVariables_Name();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.PredicatePostCondition1Impl <em>Predicate Post Condition1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.PredicatePostCondition1Impl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicatePostCondition1()
     * @generated
     */
    EClass PREDICATE_POST_CONDITION1 = eINSTANCE.getPredicatePostCondition1();

    /**
     * The meta object literal for the '<em><b>Condition11</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION1__CONDITION11 = eINSTANCE.getPredicatePostCondition1_Condition11();

    /**
     * The meta object literal for the '<em><b>Condition12</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION1__CONDITION12 = eINSTANCE.getPredicatePostCondition1_Condition12();

    /**
     * The meta object literal for the '<em><b>Condition13</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION1__CONDITION13 = eINSTANCE.getPredicatePostCondition1_Condition13();

    /**
     * The meta object literal for the '{@link model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl <em>Predicate Post Condition2</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl
     * @see model.myzdsl.myZDsl.impl.MyZDslPackageImpl#getPredicatePostCondition2()
     * @generated
     */
    EClass PREDICATE_POST_CONDITION2 = eINSTANCE.getPredicatePostCondition2();

    /**
     * The meta object literal for the '<em><b>Condition21</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION2__CONDITION21 = eINSTANCE.getPredicatePostCondition2_Condition21();

    /**
     * The meta object literal for the '<em><b>Condition22</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION2__CONDITION22 = eINSTANCE.getPredicatePostCondition2_Condition22();

    /**
     * The meta object literal for the '<em><b>Condition23</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_POST_CONDITION2__CONDITION23 = eINSTANCE.getPredicatePostCondition2_Condition23();

  }

} //MyZDslPackage
