/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>My ZModel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.MyZModel#getSystemstatespace <em>Systemstatespace</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.MyZModel#getInitialstate <em>Initialstate</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.MyZModel#getSchemas <em>Schemas</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getMyZModel()
 * @model
 * @generated
 */
public interface MyZModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Systemstatespace</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.SystemStateSpace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Systemstatespace</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getMyZModel_Systemstatespace()
   * @model containment="true"
   * @generated
   */
  EList<SystemStateSpace> getSystemstatespace();

  /**
   * Returns the value of the '<em><b>Initialstate</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.InitialState}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialstate</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getMyZModel_Initialstate()
   * @model containment="true"
   * @generated
   */
  EList<InitialState> getInitialstate();

  /**
   * Returns the value of the '<em><b>Schemas</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.Schema}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schemas</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getMyZModel_Schemas()
   * @model containment="true"
   * @generated
   */
  EList<Schema> getSchemas();

} // MyZModel
