/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Post Condition1</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition11 <em>Condition11</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition12 <em>Condition12</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition13 <em>Condition13</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition1()
 * @model
 * @generated
 */
public interface PredicatePostCondition1 extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition11</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition11</em>' containment reference.
   * @see #setCondition11(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition1_Condition11()
   * @model containment="true"
   * @generated
   */
  Variables getCondition11();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition11 <em>Condition11</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition11</em>' containment reference.
   * @see #getCondition11()
   * @generated
   */
  void setCondition11(Variables value);

  /**
   * Returns the value of the '<em><b>Condition12</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition12</em>' containment reference.
   * @see #setCondition12(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition1_Condition12()
   * @model containment="true"
   * @generated
   */
  Variables getCondition12();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition12 <em>Condition12</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition12</em>' containment reference.
   * @see #getCondition12()
   * @generated
   */
  void setCondition12(Variables value);

  /**
   * Returns the value of the '<em><b>Condition13</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition13</em>' containment reference.
   * @see #setCondition13(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition1_Condition13()
   * @model containment="true"
   * @generated
   */
  Variables getCondition13();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition1#getCondition13 <em>Condition13</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition13</em>' containment reference.
   * @see #getCondition13()
   * @generated
   */
  void setCondition13(Variables value);

} // PredicatePostCondition1
