/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Post Condition2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition21 <em>Condition21</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition22 <em>Condition22</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition23 <em>Condition23</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition2()
 * @model
 * @generated
 */
public interface PredicatePostCondition2 extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition21</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition21</em>' containment reference.
   * @see #setCondition21(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition2_Condition21()
   * @model containment="true"
   * @generated
   */
  Variables getCondition21();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition21 <em>Condition21</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition21</em>' containment reference.
   * @see #getCondition21()
   * @generated
   */
  void setCondition21(Variables value);

  /**
   * Returns the value of the '<em><b>Condition22</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition22</em>' containment reference.
   * @see #setCondition22(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition2_Condition22()
   * @model containment="true"
   * @generated
   */
  Variables getCondition22();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition22 <em>Condition22</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition22</em>' containment reference.
   * @see #getCondition22()
   * @generated
   */
  void setCondition22(Variables value);

  /**
   * Returns the value of the '<em><b>Condition23</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition23</em>' containment reference.
   * @see #setCondition23(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getPredicatePostCondition2_Condition23()
   * @model containment="true"
   * @generated
   */
  Variables getCondition23();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.PredicatePostCondition2#getCondition23 <em>Condition23</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition23</em>' containment reference.
   * @see #getCondition23()
   * @generated
   */
  void setCondition23(Variables value);

} // PredicatePostCondition2
