/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getName <em>Name</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getState <em>State</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getNameSchema <em>Name Schema</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getVarsInput <em>Vars Input</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getVarsOutput <em>Vars Output</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.Schema#getPredicates <em>Predicates</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema()
 * @model
 * @generated
 */
public interface Schema extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.Schema#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see #setState(String)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_State()
   * @model
   * @generated
   */
  String getState();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.Schema#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see #getState()
   * @generated
   */
  void setState(String value);

  /**
   * Returns the value of the '<em><b>Name Schema</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Schema</em>' attribute.
   * @see #setNameSchema(String)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_NameSchema()
   * @model
   * @generated
   */
  String getNameSchema();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.Schema#getNameSchema <em>Name Schema</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Schema</em>' attribute.
   * @see #getNameSchema()
   * @generated
   */
  void setNameSchema(String value);

  /**
   * Returns the value of the '<em><b>Vars Input</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.Variables}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars Input</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_VarsInput()
   * @model containment="true"
   * @generated
   */
  EList<Variables> getVarsInput();

  /**
   * Returns the value of the '<em><b>Vars Output</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.Variables}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars Output</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_VarsOutput()
   * @model containment="true"
   * @generated
   */
  EList<Variables> getVarsOutput();

  /**
   * Returns the value of the '<em><b>Predicates</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.Predicate}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicates</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSchema_Predicates()
   * @model containment="true"
   * @generated
   */
  EList<Predicate> getPredicates();

} // Schema
