/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System State Space Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getVas <em>Vas</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getFunction <em>Function</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getPredicateVar <em>Predicate Var</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getSystemStateSpacePredicate()
 * @model
 * @generated
 */
public interface SystemStateSpacePredicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Vas</b></em>' containment reference list.
   * The list contents are of type {@link model.myzdsl.myZDsl.Variables}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vas</em>' containment reference list.
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSystemStateSpacePredicate_Vas()
   * @model containment="true"
   * @generated
   */
  EList<Variables> getVas();

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSystemStateSpacePredicate_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Predicate Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate Var</em>' containment reference.
   * @see #setPredicateVar(Variables)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getSystemStateSpacePredicate_PredicateVar()
   * @model containment="true"
   * @generated
   */
  Variables getPredicateVar();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.SystemStateSpacePredicate#getPredicateVar <em>Predicate Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate Var</em>' containment reference.
   * @see #getPredicateVar()
   * @generated
   */
  void setPredicateVar(Variables value);

} // SystemStateSpacePredicate
