/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variables</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.Variables#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see model.myzdsl.myZDsl.MyZDslPackage#getVariables()
 * @model
 * @generated
 */
public interface Variables extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see model.myzdsl.myZDsl.MyZDslPackage#getVariables_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link model.myzdsl.myZDsl.Variables#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Variables
