/*
 * generated by Xtext 2.25.0
 */
package model.myzdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyZDslScopeProvider extends DelegatingScopeProvider {
}
