/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl.impl;

import java.util.Collection;

import model.myzdsl.myZDsl.InitialState;
import model.myzdsl.myZDsl.MyZDslPackage;
import model.myzdsl.myZDsl.MyZModel;
import model.myzdsl.myZDsl.Schema;
import model.myzdsl.myZDsl.SystemStateSpace;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>My ZModel</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.impl.MyZModelImpl#getSystemstatespace <em>Systemstatespace</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.impl.MyZModelImpl#getInitialstate <em>Initialstate</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.impl.MyZModelImpl#getSchemas <em>Schemas</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MyZModelImpl extends MinimalEObjectImpl.Container implements MyZModel
{
  /**
   * The cached value of the '{@link #getSystemstatespace() <em>Systemstatespace</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystemstatespace()
   * @generated
   * @ordered
   */
  protected EList<SystemStateSpace> systemstatespace;

  /**
   * The cached value of the '{@link #getInitialstate() <em>Initialstate</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitialstate()
   * @generated
   * @ordered
   */
  protected EList<InitialState> initialstate;

  /**
   * The cached value of the '{@link #getSchemas() <em>Schemas</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSchemas()
   * @generated
   * @ordered
   */
  protected EList<Schema> schemas;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MyZModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyZDslPackage.Literals.MY_ZMODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SystemStateSpace> getSystemstatespace()
  {
    if (systemstatespace == null)
    {
      systemstatespace = new EObjectContainmentEList<SystemStateSpace>(SystemStateSpace.class, this, MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE);
    }
    return systemstatespace;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<InitialState> getInitialstate()
  {
    if (initialstate == null)
    {
      initialstate = new EObjectContainmentEList<InitialState>(InitialState.class, this, MyZDslPackage.MY_ZMODEL__INITIALSTATE);
    }
    return initialstate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Schema> getSchemas()
  {
    if (schemas == null)
    {
      schemas = new EObjectContainmentEList<Schema>(Schema.class, this, MyZDslPackage.MY_ZMODEL__SCHEMAS);
    }
    return schemas;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE:
        return ((InternalEList<?>)getSystemstatespace()).basicRemove(otherEnd, msgs);
      case MyZDslPackage.MY_ZMODEL__INITIALSTATE:
        return ((InternalEList<?>)getInitialstate()).basicRemove(otherEnd, msgs);
      case MyZDslPackage.MY_ZMODEL__SCHEMAS:
        return ((InternalEList<?>)getSchemas()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE:
        return getSystemstatespace();
      case MyZDslPackage.MY_ZMODEL__INITIALSTATE:
        return getInitialstate();
      case MyZDslPackage.MY_ZMODEL__SCHEMAS:
        return getSchemas();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE:
        getSystemstatespace().clear();
        getSystemstatespace().addAll((Collection<? extends SystemStateSpace>)newValue);
        return;
      case MyZDslPackage.MY_ZMODEL__INITIALSTATE:
        getInitialstate().clear();
        getInitialstate().addAll((Collection<? extends InitialState>)newValue);
        return;
      case MyZDslPackage.MY_ZMODEL__SCHEMAS:
        getSchemas().clear();
        getSchemas().addAll((Collection<? extends Schema>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE:
        getSystemstatespace().clear();
        return;
      case MyZDslPackage.MY_ZMODEL__INITIALSTATE:
        getInitialstate().clear();
        return;
      case MyZDslPackage.MY_ZMODEL__SCHEMAS:
        getSchemas().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyZDslPackage.MY_ZMODEL__SYSTEMSTATESPACE:
        return systemstatespace != null && !systemstatespace.isEmpty();
      case MyZDslPackage.MY_ZMODEL__INITIALSTATE:
        return initialstate != null && !initialstate.isEmpty();
      case MyZDslPackage.MY_ZMODEL__SCHEMAS:
        return schemas != null && !schemas.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MyZModelImpl
