/**
 * generated by Xtext 2.25.0
 */
package model.myzdsl.myZDsl.impl;

import model.myzdsl.myZDsl.MyZDslPackage;
import model.myzdsl.myZDsl.PredicatePostCondition2;
import model.myzdsl.myZDsl.Variables;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Predicate Post Condition2</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl#getCondition21 <em>Condition21</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl#getCondition22 <em>Condition22</em>}</li>
 *   <li>{@link model.myzdsl.myZDsl.impl.PredicatePostCondition2Impl#getCondition23 <em>Condition23</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PredicatePostCondition2Impl extends MinimalEObjectImpl.Container implements PredicatePostCondition2
{
  /**
   * The cached value of the '{@link #getCondition21() <em>Condition21</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition21()
   * @generated
   * @ordered
   */
  protected Variables condition21;

  /**
   * The cached value of the '{@link #getCondition22() <em>Condition22</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition22()
   * @generated
   * @ordered
   */
  protected Variables condition22;

  /**
   * The cached value of the '{@link #getCondition23() <em>Condition23</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCondition23()
   * @generated
   * @ordered
   */
  protected Variables condition23;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PredicatePostCondition2Impl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyZDslPackage.Literals.PREDICATE_POST_CONDITION2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variables getCondition21()
  {
    return condition21;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCondition21(Variables newCondition21, NotificationChain msgs)
  {
    Variables oldCondition21 = condition21;
    condition21 = newCondition21;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21, oldCondition21, newCondition21);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition21(Variables newCondition21)
  {
    if (newCondition21 != condition21)
    {
      NotificationChain msgs = null;
      if (condition21 != null)
        msgs = ((InternalEObject)condition21).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21, null, msgs);
      if (newCondition21 != null)
        msgs = ((InternalEObject)newCondition21).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21, null, msgs);
      msgs = basicSetCondition21(newCondition21, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21, newCondition21, newCondition21));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variables getCondition22()
  {
    return condition22;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCondition22(Variables newCondition22, NotificationChain msgs)
  {
    Variables oldCondition22 = condition22;
    condition22 = newCondition22;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22, oldCondition22, newCondition22);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition22(Variables newCondition22)
  {
    if (newCondition22 != condition22)
    {
      NotificationChain msgs = null;
      if (condition22 != null)
        msgs = ((InternalEObject)condition22).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22, null, msgs);
      if (newCondition22 != null)
        msgs = ((InternalEObject)newCondition22).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22, null, msgs);
      msgs = basicSetCondition22(newCondition22, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22, newCondition22, newCondition22));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Variables getCondition23()
  {
    return condition23;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCondition23(Variables newCondition23, NotificationChain msgs)
  {
    Variables oldCondition23 = condition23;
    condition23 = newCondition23;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23, oldCondition23, newCondition23);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCondition23(Variables newCondition23)
  {
    if (newCondition23 != condition23)
    {
      NotificationChain msgs = null;
      if (condition23 != null)
        msgs = ((InternalEObject)condition23).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23, null, msgs);
      if (newCondition23 != null)
        msgs = ((InternalEObject)newCondition23).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23, null, msgs);
      msgs = basicSetCondition23(newCondition23, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23, newCondition23, newCondition23));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21:
        return basicSetCondition21(null, msgs);
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22:
        return basicSetCondition22(null, msgs);
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23:
        return basicSetCondition23(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21:
        return getCondition21();
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22:
        return getCondition22();
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23:
        return getCondition23();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21:
        setCondition21((Variables)newValue);
        return;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22:
        setCondition22((Variables)newValue);
        return;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23:
        setCondition23((Variables)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21:
        setCondition21((Variables)null);
        return;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22:
        setCondition22((Variables)null);
        return;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23:
        setCondition23((Variables)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION21:
        return condition21 != null;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION22:
        return condition22 != null;
      case MyZDslPackage.PREDICATE_POST_CONDITION2__CONDITION23:
        return condition23 != null;
    }
    return super.eIsSet(featureID);
  }

} //PredicatePostCondition2Impl
