/*
 * generated by Xtext 2.25.0
 */
package model.myzdsl.ui.tests;

import com.google.inject.Injector;
import model.myz.ui.internal.MyzActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyZDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyzActivator.getInstance().getInjector("model.myzdsl.MyZDsl");
	}

}
